/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Cashier;

import View.components.CashNavbarPanel;
import View.components.CashSidebarPanel;
import model.User;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author nityayadav
 */
public class CashMainFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(CashMainFrame.class.getName());

    private CashSidebarPanel cashSidebarPanel;
    private CashNavbarPanel cashNavbarPanel;
    private JPanel contentPanel;
    private CardLayout cardLayout;

    private User loggedInUser;

    public CashMainFrame() {
        this(null); // Default to null user if not provided
    }

    public CashMainFrame(User user) {
        this.loggedInUser = user;
        initComponents();
        initializeMainFrame();
    }

    private void initializeMainFrame() {
        getContentPane().setLayout(new BorderLayout());

        setTitle("PharmaStock Pro - Cashier");
        setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        setMinimumSize(new java.awt.Dimension(1200, 800));

        // Fixed Sidebar (pass 'this' for navigation)
        cashSidebarPanel = new CashSidebarPanel(this);
        getContentPane().add(cashSidebarPanel, BorderLayout.WEST);

        // Right wrapper
        JPanel rightWrapper = new JPanel(new BorderLayout());
        rightWrapper.setBackground(new Color(240, 242, 245));

        // Fixed Navbar
        cashNavbarPanel = new CashNavbarPanel();
        rightWrapper.add(cashNavbarPanel, BorderLayout.NORTH);

        // Content panel with CardLayout
        cardLayout = new CardLayout();
        contentPanel = new JPanel(cardLayout);
        rightWrapper.add(contentPanel, BorderLayout.CENTER);

        getContentPane().add(rightWrapper, BorderLayout.CENTER);

        // Add all Cashier pages as JPanels
        contentPanel.add(new CashDashboardPanel().getContentPanel(), "Dashboard");
        contentPanel.add(new CashProductPanel().getContentPanel(), "Product");
        contentPanel.add(new CashOrderPanel().getContentPanel(), "Order");

        // Pass loggedInUser to Account Panel
        contentPanel.add(new CashAccountPanel(loggedInUser).getContentPanel(), "Account");

        // Show default Dashboard
        cardLayout.show(contentPanel, "Dashboard");
        cashSidebarPanel.setActiveButton("Dashboard");

        revalidate();
        repaint();
        setLocationRelativeTo(null);
    }

    private void addPage(JPanel pageContent, String name) {
        contentPanel.add(pageContent, name);
    }

    public void switchPage(String pageName) {
        cardLayout.show(contentPanel, pageName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents
  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(CashMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new CashMainFrame().setVisible(true);
        });
    }
}
