/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import View.Admin.AdminContentPanel;
import View.Cashier.CashContentPanel;
import controller.UserController;
import model.User;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * The primary frame for the PharmaStock application.
 * Manages the login interface and handles transitions between
 * Admin and Cashier dashboards using a dynamic JContent swapping strategy.
 * 
 * @author nityayadav
 */
public class WelcomeView extends javax.swing.JFrame {

        private static final java.util.logging.Logger logger = java.util.logging.Logger
                        .getLogger(WelcomeView.class.getName());
        private UserController userController;
        private JPanel loginContentPanel;

        private AdminContentPanel adminContent;
        private CashContentPanel cashierContent;

        /**
         * Creates new form WelcomeView
         */
        public WelcomeView() {
                initComponents();
                userController = new UserController();

                loginContentPanel = jPanel1;
                // setLocationRelativeTo(null);
        }

        /**
         * Called after successful login — switches to admin or cashier view
         */
        public void showAdminView() {
                getContentPane().removeAll();
                getContentPane().setLayout(new java.awt.BorderLayout());

                if (adminContent == null) {
                        adminContent = new AdminContentPanel(this); // pass 'this' so sidebar can call back
                }

                getContentPane().add(adminContent, BorderLayout.CENTER);
                revalidate();
                repaint();

                // maximize or set bigger size for dashboard
                setExtendedState(MAXIMIZED_BOTH);
        }

        /**
         * Called after successful cashier login
         */
        public void showCashierView(User loggedInUser) {
                getContentPane().removeAll();
                getContentPane().setLayout(new java.awt.BorderLayout()); // Fix: Set layout after removeAll

                if (cashierContent == null) {
                        cashierContent = new CashContentPanel(this, loggedInUser);
                }

                getContentPane().add(cashierContent, BorderLayout.CENTER);
                revalidate();
                repaint();

                setExtendedState(MAXIMIZED_BOTH);
        }

        /**
         * Called from sidebar logout button — returns to login screen
         */
        public void showLoginScreen() {
                getContentPane().removeAll();
                getContentPane().setLayout(new java.awt.BorderLayout()); // Set layout after removeAll

                getContentPane().add(loginContentPanel, BorderLayout.CENTER);

                // Optional: clear fields
                jTextField3.setText("");
                jPasswordField1.setText("");

                // Optional: reset role toggle to default (Admin selected)
                jToggleButton1.setSelected(true);
                jToggleButton2.setSelected(false);

                // Fix: Navigation bug by resetting active panels on logout
                adminContent = null;
                cashierContent = null;

                revalidate();
                repaint();

                // Restore initial maximized state to match startup behavior
                setExtendedState(MAXIMIZED_BOTH);
        }

        /**
         * Called from sidebar when user clicks a menu item Forwards the request to
         * the currently visible content panel
         */
        public void switchPage(String pageName) {
                if (adminContent != null && adminContent.isVisible()) {
                        adminContent.switchPage(pageName);
                } else if (cashierContent != null && cashierContent.isVisible()) {
                        cashierContent.switchPage(pageName);
                }
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPopupMenu1 = new javax.swing.JPopupMenu();
                buttonGroup1 = new javax.swing.ButtonGroup();
                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jTextField3 = new javax.swing.JTextField();
                jPasswordField1 = new javax.swing.JPasswordField();
                jButton1 = new javax.swing.JButton();
                jPanel4 = new javax.swing.JPanel();
                jToggleButton1 = new javax.swing.JToggleButton();
                jToggleButton2 = new javax.swing.JToggleButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setExtendedState(6);
                setFocusCycleRoot(false);

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));

                jPanel2.setBackground(new java.awt.Color(14, 40, 107));

                jLabel1.setBackground(new java.awt.Color(0, 255, 255));
                jLabel1.setFont(new java.awt.Font("InaiMathi", 1, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("PharmaStock");

                jLabel2.setFont(new java.awt.Font("InaiMathi", 1, 18)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(186, 186, 186));
                jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jLabel2.setText("<html> Your one stop for Pharmacy for Trusted and  <br> reliable service </html>");

                jLabel3.setFont(new java.awt.Font("InaiMathi", 1, 10)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(186, 186, 186));
                jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel3.setText("© 2025 PharmaStock. Privacy Policy | Copyright Policy");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(41, 41, 41)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                181,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel2,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                608,
                                                                                                Short.MAX_VALUE))
                                                                .addGap(20, 20, 20))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(96, 96, 96)
                                                                .addComponent(jLabel3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                265,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(50, 50, 50)
                                                                .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                48,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                78,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jLabel3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                23,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));

                jLabel4.setFont(new java.awt.Font("InaiMathi", 1, 24)); // NOI18N
                jLabel4.setText("Welcome");

                jLabel5.setFont(new java.awt.Font("InaiMathi", 1, 18)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(117, 117, 117));
                jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jLabel5.setText("Please select your role to log in");

                jLabel6.setFont(new java.awt.Font("InaiMathi", 1, 18)); // NOI18N
                jLabel6.setText("Username");

                jLabel7.setFont(new java.awt.Font("InaiMathi", 1, 18)); // NOI18N
                jLabel7.setText("Password");

                jTextField3.setBackground(new java.awt.Color(173, 173, 173));
                jTextField3.setFont(new java.awt.Font("InaiMathi", 0, 13)); // NOI18N
                jTextField3.setToolTipText("");
                jTextField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(173, 173, 173), 5, true));
                jTextField3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
                jTextField3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextField3ActionPerformed(evt);
                        }
                });

                jPasswordField1.setBackground(new java.awt.Color(173, 173, 173));
                jPasswordField1.setBorder(
                                new javax.swing.border.LineBorder(new java.awt.Color(173, 173, 173), 5, true));

                jButton1.setBackground(new java.awt.Color(14, 40, 107));
                jButton1.setFont(new java.awt.Font("InaiMathi", 1, 14)); // NOI18N
                jButton1.setForeground(new java.awt.Color(255, 255, 255));
                jButton1.setText("Log in");
                jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
                jButton1.setFocusPainted(false);
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jPanel4.setBackground(new java.awt.Color(255, 255, 255));
                jPanel4.setLayout(new java.awt.GridLayout(1, 2));

                jToggleButton1.setBackground(new java.awt.Color(211, 211, 211));
                buttonGroup1.add(jToggleButton1);
                jToggleButton1.setFont(new java.awt.Font("InaiMathi", 1, 18)); // NOI18N
                jToggleButton1.setSelected(true);
                jToggleButton1.setText("Admin");
                jToggleButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
                jToggleButton1.setFocusPainted(false);
                jPanel4.add(jToggleButton1);

                buttonGroup1.add(jToggleButton2);
                jToggleButton2.setFont(new java.awt.Font("InaiMathi", 1, 18)); // NOI18N
                jToggleButton2.setText("Cashier");
                jToggleButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
                jToggleButton2.setFocusPainted(false);
                jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jToggleButton2ActionPerformed(evt);
                        }
                });
                jPanel4.add(jToggleButton2);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(184, 184, 184)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel6,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                100,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jPanel4,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                339,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jTextField3,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                315,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel5,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                315,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel4,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                100,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel7,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                100,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jPasswordField1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                315,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jButton1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                315,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(131, Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap(143, Short.MAX_VALUE)
                                                                .addComponent(jLabel4)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel5)
                                                                .addGap(31, 31, 31)
                                                                .addComponent(jPanel4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                35,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(49, 49, 49)
                                                                .addComponent(jLabel6)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jTextField3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                29,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(41, 41, 41)
                                                                .addComponent(jLabel7)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPasswordField1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                29,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(38, 38, 38)
                                                                .addComponent(jButton1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                33,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(274, 274, 274)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE));

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jToggleButton2ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jToggleButton2ActionPerformed

        private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField3ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jTextField3ActionPerformed

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed

                String email = jTextField3.getText().trim();
                String password = new String(jPasswordField1.getPassword()).trim();

                if (email.isEmpty() || password.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Please enter email and password!", "Error",
                                        JOptionPane.ERROR_MESSAGE);
                        return;
                }

                String selectedRole = jToggleButton1.isSelected() ? "Admin" : "Cashier";

                User user = userController.login(email, password);

                if (user != null && user.getRole().equals(selectedRole)) {
                        JOptionPane.showMessageDialog(this,
                                        "Login successful! Welcome, " + user.getName(),
                                        "Success", JOptionPane.INFORMATION_MESSAGE);

                        // ─── SWITCH CONTENT INSIDE SAME WINDOW ───
                        if (user.getRole().equals("Admin")) {
                                showAdminView();
                        } else if (user.getRole().equals("Cashier")) {
                                showCashierView(user);
                        }
                } else {
                        JOptionPane.showMessageDialog(this,
                                        "Invalid email, password, or role!",
                                        "Login Failed", JOptionPane.ERROR_MESSAGE);
                }
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
                        logger.log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(() -> new WelcomeView().setVisible(true));
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.ButtonGroup buttonGroup1;
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPasswordField jPasswordField1;
        private javax.swing.JPopupMenu jPopupMenu1;
        private javax.swing.JTextField jTextField3;
        private javax.swing.JToggleButton jToggleButton1;
        private javax.swing.JToggleButton jToggleButton2;
        // End of variables declaration//GEN-END:variables
}
