/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Admin;

import View.components.SidebarPanel;
import View.components.NavbarPanel;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.BorderLayout;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.BorderFactory;

/**
 *
 * @author nityayadav
 */
public class AdminCategory extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminCategory.class.getName());
    private SidebarPanel sidebarPanel;
    private NavbarPanel navbarPanel;
    private JPanel mainContentPanel;

    /**
     * Creates new form AdminCategory
     */
    public AdminCategory() {
        initComponents();
        initializeCategory();
    }

    private void initializeCategory() {
        // Main frame layout
        getContentPane().setLayout(new BorderLayout());

        setTitle("PharmaStock Pro - Categories");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setMinimumSize(new Dimension(1200, 800));

        // 1. Create Sidebar (full height on left)
        sidebarPanel = new SidebarPanel();
        sidebarPanel.setActiveButton("Categories");
        getContentPane().add(sidebarPanel, BorderLayout.WEST);

        // Highlight "Categories" in sidebar
        sidebarPanel.setActiveButton("Categories");  // <--- This line highlights Categories

        // 2. Create RIGHT WRAPPER: Navbar + Content
        JPanel rightWrapper = new JPanel(new BorderLayout());
        rightWrapper.setBackground(new Color(240, 242, 245));

        // Navbar
        navbarPanel = new NavbarPanel();
        rightWrapper.add(navbarPanel, BorderLayout.NORTH);

        // Main content for Categories page
        mainContentPanel = createCategoryContent();
        rightWrapper.add(mainContentPanel, BorderLayout.CENTER);

        // Add right wrapper to frame
        getContentPane().add(rightWrapper, BorderLayout.CENTER);

        revalidate();
        repaint();
    }

    private JPanel createCategoryContent() {
        JPanel panel = new JPanel(new BorderLayout());
        panel.setBackground(new Color(240, 242, 245));

        // Header - Categories Page
        JLabel headerLabel = new JLabel("Categories Management", SwingConstants.CENTER);
        headerLabel.setFont(new Font("SansSerif", Font.BOLD, 32));
        headerLabel.setForeground(new Color(0x0E, 0x28, 0x6B));
        headerLabel.setBorder(BorderFactory.createEmptyBorder(30, 0, 40, 0));
        panel.add(headerLabel, BorderLayout.NORTH);

        // Placeholder content (you'll replace this with real category table/form later)
        JPanel placeholder = new JPanel();
        placeholder.setLayout(new BorderLayout());
        placeholder.setBackground(Color.WHITE);
        placeholder.setBorder(BorderFactory.createEmptyBorder(40, 60, 40, 60));

        JLabel placeholderLabel = new JLabel("Categories List / Add / Edit Form Will Go Here", SwingConstants.CENTER);
        placeholderLabel.setFont(new Font("SansSerif", Font.PLAIN, 24));
        placeholderLabel.setForeground(Color.GRAY);
        placeholder.add(placeholderLabel, BorderLayout.CENTER);

        panel.add(placeholder, BorderLayout.CENTER);

        return panel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new AdminCategory().setVisible(true));
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(AdminCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new AdminCategory().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
